<?php

use App\Models\Event\MemberSSA\OrgChart;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Log;

class OrgChartSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $values = [
            ['zone' => 'Unknown', 'zone_abbr' => 'UNK', 'chapter' => 'Unknown', 'chapter_abbr' => 'UNK'],
            ['rhq' => 'RHQ1', 'rhq_abbr' => 'H1', 'zone' => 'Bedok', 'zone_abbr' => 'BDK', 'chapter' => 'Bedok Central', 'chapter_abbr' => 'BC', 'district' => 4],
            ['rhq' => 'RHQ1', 'rhq_abbr' => 'H1', 'zone' => 'Bedok', 'zone_abbr' => 'BDK', 'chapter' => 'Bedok East', 'chapter_abbr' => 'BE', 'district' => 4],
            ['rhq' => 'RHQ1', 'rhq_abbr' => 'H1', 'zone' => 'Bedok', 'zone_abbr' => 'BDK', 'chapter' => 'Bedok Rise', 'chapter_abbr' => 'BRS', 'district' => 4],
            ['rhq' => 'RHQ1', 'rhq_abbr' => 'H1', 'zone' => 'Bedok', 'zone_abbr' => 'BDK', 'chapter' => 'Bedok Vista', 'chapter_abbr' => 'BDV', 'district' => 6],
            ['rhq' => 'RHQ1', 'rhq_abbr' => 'H1', 'zone' => 'Bedok', 'zone_abbr' => 'BDK', 'chapter' => 'Bedok West', 'chapter_abbr' => 'BW', 'district' => 4],
            ['rhq' => 'RHQ1', 'rhq_abbr' => 'H1', 'zone' => 'East Coast', 'zone_abbr' => 'ECT', 'chapter' => 'Bedok South', 'chapter_abbr' => 'BS', 'district' => 6],
            ['rhq' => 'RHQ1', 'rhq_abbr' => 'H1', 'zone' => 'East Coast', 'zone_abbr' => 'ECT', 'chapter' => 'Katong', 'chapter_abbr' => 'KAT', 'district' => 4],
            ['rhq' => 'RHQ1', 'rhq_abbr' => 'H1', 'zone' => 'East Coast', 'zone_abbr' => 'ECT', 'chapter' => 'Marine Parade', 'chapter_abbr' => 'MP', 'district' => 4],
            ['rhq' => 'RHQ1', 'rhq_abbr' => 'H1', 'zone' => 'East Coast', 'zone_abbr' => 'ECT', 'chapter' => 'Siglap', 'chapter_abbr' => 'SIG', 'district' => 5],
            ['rhq' => 'RHQ1', 'rhq_abbr' => 'H1', 'zone' => 'Tampines', 'zone_abbr' => 'TAM', 'chapter' => 'Pasir Ris', 'chapter_abbr' => 'PR', 'district' => 5],
            ['rhq' => 'RHQ1', 'rhq_abbr' => 'H1', 'zone' => 'Tampines', 'zone_abbr' => 'TAM', 'chapter' => 'Tampines Central', 'chapter_abbr' => 'TPC', 'district' => 4],
            ['rhq' => 'RHQ1', 'rhq_abbr' => 'H1', 'zone' => 'Tampines', 'zone_abbr' => 'TAM', 'chapter' => 'Tampines East', 'chapter_abbr' => 'TPE', 'district' => 5],
            ['rhq' => 'RHQ1', 'rhq_abbr' => 'H1', 'zone' => 'Tampines', 'zone_abbr' => 'TAM', 'chapter' => 'Tampines North', 'chapter_abbr' => 'TPN', 'district' => 4],
            ['rhq' => 'RHQ1', 'rhq_abbr' => 'H1', 'zone' => 'Tampines', 'zone_abbr' => 'TAM', 'chapter' => 'Tampines West', 'chapter_abbr' => 'TPW', 'district' => 4],
            ['rhq' => 'RHQ1', 'rhq_abbr' => 'H1', 'zone' => 'Tanah Merah', 'zone_abbr' => 'TNM', 'chapter' => 'Tanah Merah Central', 'chapter_abbr' => 'TMC', 'district' => 5],
            ['rhq' => 'RHQ1', 'rhq_abbr' => 'H1', 'zone' => 'Tanah Merah', 'zone_abbr' => 'TNM', 'chapter' => 'Tanah Merah East', 'chapter_abbr' => 'TME', 'district' => 4],
            ['rhq' => 'RHQ1', 'rhq_abbr' => 'H1', 'zone' => 'Tanah Merah', 'zone_abbr' => 'TNM', 'chapter' => 'Tanah Merah Garden', 'chapter_abbr' => 'TMG', 'district' => 4],
            ['rhq' => 'RHQ2', 'rhq_abbr' => 'H2', 'zone' => 'Ang Mo Kio', 'zone_abbr' => 'AMK', 'chapter' => 'Ang Mo Kio Central', 'chapter_abbr' => 'AMC', 'district' => 4],
            ['rhq' => 'RHQ2', 'rhq_abbr' => 'H2', 'zone' => 'Ang Mo Kio', 'zone_abbr' => 'AMK', 'chapter' => 'Ang Mo Kio East', 'chapter_abbr' => 'AME', 'district' => 5],
            ['rhq' => 'RHQ2', 'rhq_abbr' => 'H2', 'zone' => 'Ang Mo Kio', 'zone_abbr' => 'AMK', 'chapter' => 'Ang Mo Kio North', 'chapter_abbr' => 'AMN', 'district' => 4],
            ['rhq' => 'RHQ2', 'rhq_abbr' => 'H2', 'zone' => 'Ang Mo Kio', 'zone_abbr' => 'AMK', 'chapter' => 'Ang Mo Kio South', 'chapter_abbr' => 'AMS', 'district' => 5],
            ['rhq' => 'RHQ2', 'rhq_abbr' => 'H2', 'zone' => 'Ang Mo Kio', 'zone_abbr' => 'AMK', 'chapter' => 'Ang Mo Kio West', 'chapter_abbr' => 'AMW', 'district' => 4],
            ['rhq' => 'RHQ2', 'rhq_abbr' => 'H2', 'zone' => 'Cheng San', 'zone_abbr' => 'CS', 'chapter' => 'Cheng San East', 'chapter_abbr' => 'CSE', 'district' => 4],
            ['rhq' => 'RHQ2', 'rhq_abbr' => 'H2', 'zone' => 'Cheng San', 'zone_abbr' => 'CS', 'chapter' => 'Cheng San North', 'chapter_abbr' => 'CSN', 'district' => 4],
            ['rhq' => 'RHQ2', 'rhq_abbr' => 'H2', 'zone' => 'Cheng San', 'zone_abbr' => 'CS', 'chapter' => 'Khatib', 'chapter_abbr' => 'KTB', 'district' => 4],
            ['rhq' => 'RHQ2', 'rhq_abbr' => 'H2', 'zone' => 'Cheng San', 'zone_abbr' => 'CS', 'chapter' => 'Kuo Chuan', 'chapter_abbr' => 'KC', 'district' => 4],
            ['rhq' => 'RHQ2', 'rhq_abbr' => 'H2', 'zone' => 'Cheng San', 'zone_abbr' => 'CS', 'chapter' => 'Yio Chu Kang', 'chapter_abbr' => 'YCK', 'district' => 4],
            ['rhq' => 'RHQ2', 'rhq_abbr' => 'H2', 'zone' => 'Hougang', 'zone_abbr' => 'HG', 'chapter' => 'Hougang Central', 'chapter_abbr' => 'HGC', 'district' => 4],
            ['rhq' => 'RHQ2', 'rhq_abbr' => 'H2', 'zone' => 'Hougang', 'zone_abbr' => 'HG', 'chapter' => 'Hougang South', 'chapter_abbr' => 'HGS', 'district' => 4],
            ['rhq' => 'RHQ2', 'rhq_abbr' => 'H2', 'zone' => 'Hougang', 'zone_abbr' => 'HG', 'chapter' => 'Kovan', 'chapter_abbr' => 'KOV', 'district' => 4],
            ['rhq' => 'RHQ2', 'rhq_abbr' => 'H2', 'zone' => 'Hougang', 'zone_abbr' => 'HG', 'chapter' => 'Teck Ghee', 'chapter_abbr' => 'TG', 'district' => 4],
            ['rhq' => 'RHQ2', 'rhq_abbr' => 'H2', 'zone' => 'Sengkang', 'zone_abbr' => 'SK', 'chapter' => 'Sengkang Central', 'chapter_abbr' => 'SKC', 'district' => 4],
            ['rhq' => 'RHQ2', 'rhq_abbr' => 'H2', 'zone' => 'Sengkang', 'zone_abbr' => 'SK', 'chapter' => 'Sengkang East', 'chapter_abbr' => 'SKE', 'district' => 4],
            ['rhq' => 'RHQ2', 'rhq_abbr' => 'H2', 'zone' => 'Sengkang', 'zone_abbr' => 'SK', 'chapter' => 'Sengkang South', 'chapter_abbr' => 'SKS', 'district' => 3],
            ['rhq' => 'RHQ3', 'rhq_abbr' => 'H3', 'zone' => 'Bugis', 'zone_abbr' => 'BG', 'chapter' => 'Farrer', 'chapter_abbr' => 'FRR', 'district' => 3],
            ['rhq' => 'RHQ3', 'rhq_abbr' => 'H3', 'zone' => 'Bugis', 'zone_abbr' => 'BG', 'chapter' => 'Norfolk', 'chapter_abbr' => 'NOR', 'district' => 4],
            ['rhq' => 'RHQ3', 'rhq_abbr' => 'H3', 'zone' => 'Bugis', 'zone_abbr' => 'BG', 'chapter' => 'Victoria', 'chapter_abbr' => 'VIC', 'district' => 3],
            ['rhq' => 'RHQ3', 'rhq_abbr' => 'H3', 'zone' => 'City', 'zone_abbr' => 'CIT', 'chapter' => 'Havelock', 'chapter_abbr' => 'HVL', 'district' => 4],
            ['rhq' => 'RHQ3', 'rhq_abbr' => 'H3', 'zone' => 'City', 'zone_abbr' => 'CIT', 'chapter' => 'New Bridge', 'chapter_abbr' => 'NB', 'district' => 4],
            ['rhq' => 'RHQ3', 'rhq_abbr' => 'H3', 'zone' => 'City', 'zone_abbr' => 'CIT', 'chapter' => 'Outram', 'chapter_abbr' => 'OT', 'district' => 5],
            ['rhq' => 'RHQ3', 'rhq_abbr' => 'H3', 'zone' => 'Clementi', 'zone_abbr' => 'CLM', 'chapter' => 'Buona Vista', 'chapter_abbr' => 'BV', 'district' => 4],
            ['rhq' => 'RHQ3', 'rhq_abbr' => 'H3', 'zone' => 'Clementi', 'zone_abbr' => 'CLM', 'chapter' => 'Clementi Woods', 'chapter_abbr' => 'CW', 'district' => 4],
            ['rhq' => 'RHQ3', 'rhq_abbr' => 'H3', 'zone' => 'Clementi', 'zone_abbr' => 'CLM', 'chapter' => 'Kent Ridge', 'chapter_abbr' => 'KR', 'district' => 4],
            ['rhq' => 'RHQ3', 'rhq_abbr' => 'H3', 'zone' => 'Clementi', 'zone_abbr' => 'CLM', 'chapter' => 'Nan Hua', 'chapter_abbr' => 'NH', 'district' => 4],
            ['rhq' => 'RHQ3', 'rhq_abbr' => 'H3', 'zone' => 'Delta', 'zone_abbr' => 'DT', 'chapter' => 'Bukit Purmei', 'chapter_abbr' => 'BPM', 'district' => 5],
            ['rhq' => 'RHQ3', 'rhq_abbr' => 'H3', 'zone' => 'Delta', 'zone_abbr' => 'DT', 'chapter' => 'Tiong Bahru', 'chapter_abbr' => 'TB', 'district' => 4],
            ['rhq' => 'RHQ3', 'rhq_abbr' => 'H3', 'zone' => 'Delta', 'zone_abbr' => 'DT', 'chapter' => 'Telok Blangah', 'chapter_abbr' => 'TLB', 'district' => 4],
            ['rhq' => 'RHQ3', 'rhq_abbr' => 'H3', 'zone' => 'Lavender', 'zone_abbr' => 'LAV', 'chapter' => 'Cambridge', 'chapter_abbr' => 'CAM', 'district' => 3],
            ['rhq' => 'RHQ3', 'rhq_abbr' => 'H3', 'zone' => 'Lavender', 'zone_abbr' => 'LAV', 'chapter' => 'Newton', 'chapter_abbr' => 'NT', 'district' => 3],
            ['rhq' => 'RHQ3', 'rhq_abbr' => 'H3', 'zone' => 'Lavender', 'zone_abbr' => 'LAV', 'chapter' => 'Owen', 'chapter_abbr' => 'OW', 'district' => 3],
            ['rhq' => 'RHQ3', 'rhq_abbr' => 'H3', 'zone' => 'Queenstown', 'zone_abbr' => 'QST', 'chapter' => 'Alexandra', 'chapter_abbr' => 'ALX', 'district' => 5],
            ['rhq' => 'RHQ3', 'rhq_abbr' => 'H3', 'zone' => 'Queenstown', 'zone_abbr' => 'QST', 'chapter' => 'Bukit Merah ', 'chapter_abbr' => 'BM', 'district' => 5],
            ['rhq' => 'RHQ3', 'rhq_abbr' => 'H3', 'zone' => 'Queenstown', 'zone_abbr' => 'QST', 'chapter' => 'Henderson', 'chapter_abbr' => 'HDS', 'district' => 4],
            ['rhq' => 'RHQ4', 'rhq_abbr' => 'H4', 'zone' => 'Chinese Garden', 'zone_abbr' => 'CGD', 'chapter' => 'Jurong East', 'chapter_abbr' => 'JE', 'district' => 4],
            ['rhq' => 'RHQ4', 'rhq_abbr' => 'H4', 'zone' => 'Chinese Garden', 'zone_abbr' => 'CGD', 'chapter' => 'Pandan', 'chapter_abbr' => 'PAN', 'district' => 5],
            ['rhq' => 'RHQ4', 'rhq_abbr' => 'H4', 'zone' => 'Chinese Garden', 'zone_abbr' => 'CGD', 'chapter' => 'Yu Hua', 'chapter_abbr' => 'YH', 'district' => 4],
            ['rhq' => 'RHQ4', 'rhq_abbr' => 'H4', 'zone' => 'Hong Kah', 'zone_abbr' => 'HK', 'chapter' => 'Hong Kah Central', 'chapter_abbr' => 'HKC', 'district' => 4],
            ['rhq' => 'RHQ4', 'rhq_abbr' => 'H4', 'zone' => 'Hong Kah', 'zone_abbr' => 'HK', 'chapter' => 'Lakeside', 'chapter_abbr' => 'LS', 'district' => 6],
            ['rhq' => 'RHQ4', 'rhq_abbr' => 'H4', 'zone' => 'Hong Kah', 'zone_abbr' => 'HK', 'chapter' => 'Nanyang', 'chapter_abbr' => 'NY', 'district' => 6],
            ['rhq' => 'RHQ4', 'rhq_abbr' => 'H4', 'zone' => 'Jurong', 'zone_abbr' => 'JUR', 'chapter' => 'Boon Lay', 'chapter_abbr' => 'BL', 'district' => 5],
            ['rhq' => 'RHQ4', 'rhq_abbr' => 'H4', 'zone' => 'Jurong', 'zone_abbr' => 'JUR', 'chapter' => 'Jurong Central', 'chapter_abbr' => 'JC', 'district' => 5],
            ['rhq' => 'RHQ4', 'rhq_abbr' => 'H4', 'zone' => 'Jurong', 'zone_abbr' => 'JUR', 'chapter' => 'Toh Guan', 'chapter_abbr' => 'TGN', 'district' => 5],
            ['rhq' => 'RHQ4', 'rhq_abbr' => 'H4', 'zone' => 'West Coast', 'zone_abbr' => 'WCT', 'chapter' => 'Commonwealth', 'chapter_abbr' => 'CWH', 'district' => 6],
            ['rhq' => 'RHQ4', 'rhq_abbr' => 'H4', 'zone' => 'West Coast', 'zone_abbr' => 'WCT', 'chapter' => 'Holland', 'chapter_abbr' => 'HOL', 'district' => 6],
            ['rhq' => 'RHQ4', 'rhq_abbr' => 'H4', 'zone' => 'West Coast', 'zone_abbr' => 'WCT', 'chapter' => 'Pasir Panjang', 'chapter_abbr' => 'PP', 'district' => 5],
            ['rhq' => 'RHQ5', 'rhq_abbr' => 'H5', 'zone' => 'Bishan', 'zone_abbr' => 'BIS', 'chapter' => 'Bishan Central', 'chapter_abbr' => 'BSC', 'district' => 4],
            ['rhq' => 'RHQ5', 'rhq_abbr' => 'H5', 'zone' => 'Bishan', 'zone_abbr' => 'BIS', 'chapter' => 'Bishan East', 'chapter_abbr' => 'BSE', 'district' => 4],
            ['rhq' => 'RHQ5', 'rhq_abbr' => 'H5', 'zone' => 'Bishan', 'zone_abbr' => 'BIS', 'chapter' => 'Bishan North', 'chapter_abbr' => 'BSN', 'district' => 4],
            ['rhq' => 'RHQ5', 'rhq_abbr' => 'H5', 'zone' => 'Bishan', 'zone_abbr' => 'BIS', 'chapter' => 'Bishan South', 'chapter_abbr' => 'BSS', 'district' => 4],
            ['rhq' => 'RHQ5', 'rhq_abbr' => 'H5', 'zone' => 'Bishan', 'zone_abbr' => 'BIS', 'chapter' => 'Bishan West', 'chapter_abbr' => 'BSW', 'district' => 4],
            ['rhq' => 'RHQ5', 'rhq_abbr' => 'H5', 'zone' => 'Thomson', 'zone_abbr' => 'THM', 'chapter' => 'Braddell', 'chapter_abbr' => 'BDL', 'district' => 4],
            ['rhq' => 'RHQ5', 'rhq_abbr' => 'H5', 'zone' => 'Thomson', 'zone_abbr' => 'THM', 'chapter' => 'Crawford', 'chapter_abbr' => 'CF', 'district' => 5],
            ['rhq' => 'RHQ5', 'rhq_abbr' => 'H5', 'zone' => 'Thomson', 'zone_abbr' => 'THM', 'chapter' => 'Goldhill', 'chapter_abbr' => 'GHL', 'district' => 4],
            ['rhq' => 'RHQ5', 'rhq_abbr' => 'H5', 'zone' => 'Thomson', 'zone_abbr' => 'THM', 'chapter' => 'Rochor', 'chapter_abbr' => 'ROC', 'district' => 4],
            ['rhq' => 'RHQ5', 'rhq_abbr' => 'H5', 'zone' => 'Toa Payoh', 'zone_abbr' => 'TPY', 'chapter' => 'Toa Payoh East', 'chapter_abbr' => 'TYE', 'district' => 5],
            ['rhq' => 'RHQ5', 'rhq_abbr' => 'H5', 'zone' => 'Toa Payoh', 'zone_abbr' => 'TPY', 'chapter' => 'Toa Payoh North', 'chapter_abbr' => 'TYN', 'district' => 5],
            ['rhq' => 'RHQ5', 'rhq_abbr' => 'H5', 'zone' => 'Toa Payoh', 'zone_abbr' => 'TPY', 'chapter' => 'Toa Payoh South', 'chapter_abbr' => 'TYS', 'district' => 5],
            ['rhq' => 'RHQ5', 'rhq_abbr' => 'H5', 'zone' => 'Toa Payoh', 'zone_abbr' => 'TPY', 'chapter' => 'Toa Payoh West', 'chapter_abbr' => 'TYW', 'district' => 5],
            ['rhq' => 'RHQ5', 'rhq_abbr' => 'H5', 'zone' => 'Whampoa', 'zone_abbr' => 'WHM', 'chapter' => 'Serangoon North', 'chapter_abbr' => 'SRN', 'district' => 4],
            ['rhq' => 'RHQ5', 'rhq_abbr' => 'H5', 'zone' => 'Whampoa', 'zone_abbr' => 'WHM', 'chapter' => 'Serangoon South', 'chapter_abbr' => 'SRS', 'district' => 4],
            ['rhq' => 'RHQ5', 'rhq_abbr' => 'H5', 'zone' => 'Whampoa', 'zone_abbr' => 'WHM', 'chapter' => 'Whampoa East', 'chapter_abbr' => 'WPE', 'district' => 6],
            ['rhq' => 'RHQ5', 'rhq_abbr' => 'H5', 'zone' => 'Whampoa', 'zone_abbr' => 'WHM', 'chapter' => 'Whampoa West', 'chapter_abbr' => 'WPW', 'district' => 5],
            ['rhq' => 'RHQ6', 'rhq_abbr' => 'H6', 'zone' => 'Aljunied', 'zone_abbr' => 'AJ', 'chapter' => 'Aljunied East', 'chapter_abbr' => 'AJE', 'district' => 4],
            ['rhq' => 'RHQ6', 'rhq_abbr' => 'H6', 'zone' => 'Aljunied', 'zone_abbr' => 'AJ', 'chapter' => 'Aljunied North', 'chapter_abbr' => 'AJN', 'district' => 4],
            ['rhq' => 'RHQ6', 'rhq_abbr' => 'H6', 'zone' => 'Aljunied', 'zone_abbr' => 'AJ', 'chapter' => 'Aljunied South', 'chapter_abbr' => 'AJS', 'district' => 3],
            ['rhq' => 'RHQ6', 'rhq_abbr' => 'H6', 'zone' => 'Aljunied', 'zone_abbr' => 'AJ', 'chapter' => 'Aljunied West', 'chapter_abbr' => 'AJW', 'district' => 5],
            ['rhq' => 'RHQ6', 'rhq_abbr' => 'H6', 'zone' => 'Eunos', 'zone_abbr' => 'EUN', 'chapter' => 'Eunos Central', 'chapter_abbr' => 'ENC', 'district' => 4],
            ['rhq' => 'RHQ6', 'rhq_abbr' => 'H6', 'zone' => 'Eunos', 'zone_abbr' => 'EUN', 'chapter' => 'Eunos East', 'chapter_abbr' => 'ENE', 'district' => 4],
            ['rhq' => 'RHQ6', 'rhq_abbr' => 'H6', 'zone' => 'Eunos', 'zone_abbr' => 'EUN', 'chapter' => 'Eunos South', 'chapter_abbr' => 'ENS', 'district' => 3],
            ['rhq' => 'RHQ6', 'rhq_abbr' => 'H6', 'zone' => 'Eunos', 'zone_abbr' => 'EUN', 'chapter' => 'Eunos West', 'chapter_abbr' => 'ENW', 'district' => 5],
            ['rhq' => 'RHQ6', 'rhq_abbr' => 'H6', 'zone' => 'Geylang', 'zone_abbr' => 'GEY', 'chapter' => 'Geylang Central', 'chapter_abbr' => 'GYC', 'district' => 4],
            ['rhq' => 'RHQ6', 'rhq_abbr' => 'H6', 'zone' => 'Geylang', 'zone_abbr' => 'GEY', 'chapter' => 'Geylang North', 'chapter_abbr' => 'GYN', 'district' => 4],
            ['rhq' => 'RHQ6', 'rhq_abbr' => 'H6', 'zone' => 'Geylang', 'zone_abbr' => 'GEY', 'chapter' => 'Geylang South', 'chapter_abbr' => 'GYS', 'district' => 4],
            ['rhq' => 'RHQ6', 'rhq_abbr' => 'H6', 'zone' => 'Geylang', 'zone_abbr' => 'GEY', 'chapter' => 'Geylang West', 'chapter_abbr' => 'GYW', 'district' => 5],
            ['rhq' => 'RHQ6', 'rhq_abbr' => 'H6', 'zone' => 'Geylang', 'zone_abbr' => 'GEY', 'chapter' => 'Macpherson', 'chapter_abbr' => 'MAC', 'district' => 4],
            ['rhq' => 'RHQ6', 'rhq_abbr' => 'H6', 'zone' => 'Paya Lebar', 'zone_abbr' => 'PL', 'chapter' => 'Paya Lebar East', 'chapter_abbr' => 'PLE', 'district' => 5],
            ['rhq' => 'RHQ6', 'rhq_abbr' => 'H6', 'zone' => 'Paya Lebar', 'zone_abbr' => 'PL', 'chapter' => 'Paya Lebar North', 'chapter_abbr' => 'PLN', 'district' => 5],
            ['rhq' => 'RHQ6', 'rhq_abbr' => 'H6', 'zone' => 'Paya Lebar', 'zone_abbr' => 'PL', 'chapter' => 'Paya Lebar South', 'chapter_abbr' => 'PLS', 'district' => 5],
            ['rhq' => 'RHQ6', 'rhq_abbr' => 'H6', 'zone' => 'Paya Lebar', 'zone_abbr' => 'PL', 'chapter' => 'Paya Lebar West', 'chapter_abbr' => 'PLW', 'district' => 5],
            ['rhq' => 'RHQ7', 'rhq_abbr' => 'H7', 'zone' => 'Bukit Panjang', 'zone_abbr' => 'BP', 'chapter' => 'Marsiling', 'chapter_abbr' => 'MLG', 'district' => 4],
            ['rhq' => 'RHQ7', 'rhq_abbr' => 'H7', 'zone' => 'Bukit Panjang', 'zone_abbr' => 'BP', 'chapter' => 'Woodlands', 'chapter_abbr' => 'WDS', 'district' => 5],
            ['rhq' => 'RHQ7', 'rhq_abbr' => 'H7', 'zone' => 'Bukit Panjang', 'zone_abbr' => 'BP', 'chapter' => 'Zheng Hua', 'chapter_abbr' => 'ZH', 'district' => 6],
            ['rhq' => 'RHQ7', 'rhq_abbr' => 'H7', 'zone' => 'Choa Chu Kang', 'zone_abbr' => 'CCK', 'chapter' => 'Bukit Batok', 'chapter_abbr' => 'BB', 'district' => 6],
            ['rhq' => 'RHQ7', 'rhq_abbr' => 'H7', 'zone' => 'Choa Chu Kang', 'zone_abbr' => 'CCK', 'chapter' => 'Teck Whye', 'chapter_abbr' => 'TW', 'district' => 6],
            ['rhq' => 'RHQ7', 'rhq_abbr' => 'H7', 'zone' => 'Choa Chu Kang', 'zone_abbr' => 'CCK', 'chapter' => 'Yew Tee', 'chapter_abbr' => 'YT', 'district' => 5],
            ['rhq' => 'RHQ7', 'rhq_abbr' => 'H7', 'zone' => 'Sembawang', 'zone_abbr' => 'SBW', 'chapter' => 'Admiralty', 'chapter_abbr' => 'AMT', 'district' => 7],
            ['rhq' => 'RHQ7', 'rhq_abbr' => 'H7', 'zone' => 'Sembawang', 'zone_abbr' => 'SBW', 'chapter' => 'Chong Pang', 'chapter_abbr' => 'CP', 'district' => 4],
            ['rhq' => 'RHQ7', 'rhq_abbr' => 'H7', 'zone' => 'Sembawang', 'zone_abbr' => 'SBW', 'chapter' => 'Lentor', 'chapter_abbr' => 'LT', 'district' => 5],
            ['rhq' => 'RHQ7', 'rhq_abbr' => 'H7', 'zone' => 'Sembawang', 'zone_abbr' => 'SBW', 'chapter' => 'Yishun', 'chapter_abbr' => 'YIS', 'district' => 4],
        ];

        foreach ($values as $value) {
            OrgChart::create($value);
        }

        Log::info("[Migration - Seeding] OrgChart table seeded!");
    }
}
